export interface ServiceDetail {
  slug: string;
  route: string;
  badge: string;
  title: string;
  subtitle: string;
  description: string;
  coverImage: string;
  coverAlt: string;
  caption: string;
  eyebrow: string;
  bulletPoints: string[];
  ctaText: string;
  servicePrefill: string;
  note?: string;
  relatedSlugs: string[];
}

export interface DivisionInfo {
  id: string;
  number: string;
  title: string;
  label: string;
  emblem: string;
  photo: string;
  photoAlt: string;
  photoLabel: string;
  description: string;
  tags: string[];
  route: string;
  ctaText: string;
  highlights?: string[];
}

export const ADVIORA_CONTACT = {
  whatsapp: '919945633771', // 9945633771 with India country code 91
  whatsappDisplay: '+91 99456 33771',
  email: 'kamalkv@gmail.com',
  defaultWhatsAppMessage: 'Hello ADViora, I would like to enquire about your services.',
  defaultEmailSubject: 'ADViora service enquiry',
};

export function getWhatsAppUrl(customMessage?: string): string {
  const msg = customMessage || ADVIORA_CONTACT.defaultWhatsAppMessage;
  return `https://wa.me/${ADVIORA_CONTACT.whatsapp}?text=${encodeURIComponent(msg)}`;
}

export function getEmailUrl(subject?: string): string {
  const subj = subject || ADVIORA_CONTACT.defaultEmailSubject;
  return `mailto:${ADVIORA_CONTACT.email}?subject=${encodeURIComponent(subj)}`;
}

export function getServiceEnquiryMessage(service: string): string {
  if (!service) return '';
  return `I would like to enquire about ${service.toLowerCase()}. Please share availability and scope.`;
}

export function isAutoGeneratedMessage(msg: string): boolean {
  if (!msg || !msg.trim()) return true;
  const trimmed = msg.trim();
  const pattern = /^i would like to enquire about .+\. please share availability and (fees|scope)\.?$/i;
  const defaultPattern = /^hello adviora, i would like to enquire about your services\.?$/i;
  return pattern.test(trimmed) || defaultPattern.test(trimmed);
}

export function formatEnquiryPayload(fields: {
  name: string;
  email: string;
  phone: string;
  interest: string;
  message: string;
}): string {
  return `Hello ADViora Consulting,

I would like to enquire about:
Name: ${fields.name}
Email: ${fields.email}
Phone: ${fields.phone}
Service: ${fields.interest}

Goals / Message:
${fields.message}`;
}



export const DIVISIONS: DivisionInfo[] = [
  {
    id: 'digital',
    number: '',
    title: 'ADViora Digital',
    label: 'Business & technology',
    emblem: '▦',
    photo: '/images/technology.webp',
    photoAlt: 'Laptop displaying code in a workspace',
    photoLabel: 'Strategy meets technology',
    description: 'Align strategy, processes and technology to navigate change and build lasting capability.',
    tags: ['ITSM', 'Artificial intelligence', 'Digital transformation', 'Business transformation', 'Professional training'],
    route: '/digital',
    ctaText: 'Explore ADViora Digital',
    highlights: [
      'Business priorities & transformation planning',
      'Process and operating-model improvement',
      'ITSM, AI & modern digital solutions',
      'Change readiness & organizational capability',
    ],
  },
];

export const DIGITAL_CAPABILITIES = [
  {
    number: '01',
    category: 'TRANSFORM',
    title: 'Business transformation',
    description: 'Connect your priorities, processes and operating model to a clear direction for change.',
  },
  {
    number: '02',
    category: 'SIMPLIFY',
    title: 'IT service management',
    description: 'Improve how IT services are designed, delivered and supported across your organization.',
  },
  {
    number: '03',
    category: 'ENABLE',
    title: 'AI & digital solutions',
    description: 'Identify practical opportunities for AI, automation and digital ways of working.',
  },
  {
    number: '04',
    category: 'DEVELOP',
    title: 'Professional training',
    description: 'Help teams apply new knowledge and build confidence through focused learning.',
  },
];

export const PROCESS_STEPS = [
  {
    step: '01',
    title: 'Understand',
    description: 'Start with your goals, your context and the challenges that matter.',
  },
  {
    step: '02',
    title: 'Shape the approach',
    description: 'Define the right direction, priorities and support for your journey.',
  },
  {
    step: '03',
    title: 'Put it into practice',
    description: 'Bring the plan to life through consulting, technology or training.',
  },
  {
    step: '04',
    title: 'Keep progressing',
    description: 'Review what’s working, refine the approach and build on your progress.',
  },
];

export const BRAND_MEANINGS = [
  {
    word: 'Advance',
    subtitle: 'Progress with purpose.',
    description: 'Move from ambition to action.',
  },
  {
    word: 'Vision',
    subtitle: 'See the bigger picture.',
    description: 'Let strategic thinking guide the next step.',
  },
  {
    word: 'Aura',
    subtitle: 'Make a meaningful impression.',
    description: 'Build influence, presence and excellence.',
  },
];

export const FAQ_ITEMS = [
  {
    question: 'What does ADViora Digital help with?',
    answer: 'ADViora Digital supports business transformation, IT service management, AI and digital transformation, and professional training.',
  },
  {
    question: 'Can we discuss our organization’s requirements?',
    answer: 'Yes. Share your goals and current challenges through the enquiry options so the scope and next steps can be discussed.',
  },
  {
    question: 'Does ADViora offer professional training?',
    answer: 'Yes. Professional and technology-focused training remains part of ADViora Digital, with learning needs and scope discussed for each engagement.',
  },
  {
    question: 'What does the name ADViora mean?',
    answer: 'ADViora is a coined brand name inspired conceptually by Advance, Vision and Aura: progress, strategic thinking, and influence, presence and excellence. It is a brand meaning, not an acronym.',
  },
];

export const SERVICES_DATA: Record<string, ServiceDetail> = {
  'business-transformation': {
    slug: 'business-transformation',
    route: '/business-transformation',
    badge: 'ADViora Digital · 01',
    title: 'Business transformation',
    subtitle: 'ADViora Consulting',
    description: 'Connect business priorities with the people, processes and ways of working needed to move forward. Begin with your current challenges and shape a practical direction for change.',
    coverImage: '/images/consulting.webp',
    coverAlt: 'Professionals collaborating around a table',
    caption: 'Business transformation',
    eyebrow: 'ADViora Consulting',
    bulletPoints: [
      'Business priorities and transformation planning',
      'Process and operating-model improvement',
      'Change readiness and organizational capability',
    ],
    ctaText: 'Discuss business transformation',
    servicePrefill: 'Business transformation',
    relatedSlugs: ['technology-digital', 'professional-training'],
  },
  'technology-digital': {
    slug: 'technology-digital',
    route: '/technology-digital',
    badge: 'ADViora Digital · 02',
    title: 'Technology & digital transformation',
    subtitle: 'ADViora Consulting',
    description: 'Make technology serve your organization’s goals. Explore IT service management, practical AI opportunities and digital transformation in the context of your business.',
    coverImage: '/images/technology.webp',
    coverAlt: 'Laptop showing software code in a workspace',
    caption: 'Technology & digital',
    eyebrow: 'ADViora Consulting',
    bulletPoints: [
      'ITSM: service design, delivery and improvement',
      'AI and automation opportunity assessment',
      'Digital ways of working and technology adoption',
    ],
    ctaText: 'Discuss technology requirements',
    servicePrefill: 'ITSM / AI / digital transformation',
    relatedSlugs: ['business-transformation', 'professional-training'],
  },
  'professional-training': {
    slug: 'professional-training',
    route: '/professional-training',
    badge: 'ADViora Digital · 03',
    title: 'Professional training & development',
    subtitle: 'ADViora Consulting',
    description: 'Help individuals and teams develop useful skills and apply them with confidence. Discuss learning needs across business, technology and professional practice.',
    coverImage: '/images/training.webp',
    coverAlt: 'Attendees taking notes at a professional workshop',
    caption: 'Professional development',
    eyebrow: 'ADViora Consulting',
    bulletPoints: [
      'Learning needs and programme planning',
      'Professional and technology-focused training',
      'Practical application and capability development',
    ],
    ctaText: 'Discuss a training programme',
    servicePrefill: 'Professional training',
    relatedSlugs: ['business-transformation', 'technology-digital'],
  },
};

export const ALLOWED_INTERESTS = [
  'Business transformation',
  'ITSM / AI / digital transformation',
  'Professional training',
] as const;

export type InterestArea = typeof ALLOWED_INTERESTS[number];
