'use client';

import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { FormFields } from '@/lib/validation';
import { getServiceEnquiryMessage, isAutoGeneratedMessage, ADVIORA_CONTACT } from '@/lib/data';

interface ChannelModalInfo {
  title: string;
  description: string;
  channel: 'whatsapp' | 'email';
}

interface ModalContextType {
  isEnquiryOpen: boolean;
  enquiryService: string;
  openEnquiryModal: (service?: string, triggerEl?: HTMLElement | null) => void;
  closeEnquiryModal: () => void;
  triggerElement: HTMLElement | null;
  setTriggerElement: (el: HTMLElement | null) => void;
  channelModal: ChannelModalInfo | null;
  openChannelModal: (channel: 'whatsapp' | 'email', triggerEl?: HTMLElement | null) => void;
  closeChannelModal: () => void;
  sharedFormValues: FormFields;
  setSharedFormValues: React.Dispatch<React.SetStateAction<FormFields>>;
  updateServiceInterest: (service: string) => void;
}

const initialFormValues: FormFields = {
  name: '',
  email: '',
  phone: '',
  interest: '',
  message: '',
  website: '',
};

const ModalContext = createContext<ModalContextType | undefined>(undefined);

export function ModalProvider({ children }: { children: ReactNode }) {
  const [isEnquiryOpen, setIsEnquiryOpen] = useState(false);
  const [enquiryService, setEnquiryService] = useState('');
  const [triggerElement, setTriggerElement] = useState<HTMLElement | null>(null);
  const [channelModal, setChannelModal] = useState<ChannelModalInfo | null>(null);
  const [sharedFormValues, setSharedFormValues] = useState<FormFields>(initialFormValues);

  const updateServiceInterest = useCallback((service: string) => {
    setSharedFormValues((prev) => {
      const shouldUpdateMessage = isAutoGeneratedMessage(prev.message);
      return {
        ...prev,
        interest: service,
        message: shouldUpdateMessage ? (service ? getServiceEnquiryMessage(service) : '') : prev.message,
      };
    });
  }, []);

  const openEnquiryModal = useCallback(
    (service?: string, triggerEl?: HTMLElement | null) => {
      const activeEl =
        triggerEl !== undefined
          ? triggerEl
          : typeof document !== 'undefined'
          ? (document.activeElement as HTMLElement | null)
          : null;
      setTriggerElement(activeEl);
      if (service) {
        setEnquiryService(service);
        updateServiceInterest(service);
      }
      setIsEnquiryOpen(true);
    },
    [updateServiceInterest]
  );

  const closeEnquiryModal = useCallback(() => {
    setIsEnquiryOpen(false);
  }, []);

  const openChannelModal = useCallback(
    (channel: 'whatsapp' | 'email', triggerEl?: HTMLElement | null) => {
      const activeEl =
        triggerEl !== undefined
          ? triggerEl
          : typeof document !== 'undefined'
          ? (document.activeElement as HTMLElement | null)
          : null;
      setTriggerElement(activeEl);
      if (channel === 'whatsapp') {
        setChannelModal({
          channel: 'whatsapp',
          title: 'Chat on WhatsApp',
          description: `Connect directly with ADViora on WhatsApp (${ADVIORA_CONTACT.whatsappDisplay}). Direct message: "${ADVIORA_CONTACT.defaultWhatsAppMessage}"`,
        });
      } else {
        setChannelModal({
          channel: 'email',
          title: 'Email ADViora',
          description: `Send your enquiry to ADViora at ${ADVIORA_CONTACT.email}. Direct email opens in your default mail application.`,
        });
      }
    },
    []
  );

  const closeChannelModal = useCallback(() => {
    setChannelModal(null);
  }, []);

  return (
    <ModalContext.Provider
      value={{
        isEnquiryOpen,
        enquiryService,
        openEnquiryModal,
        closeEnquiryModal,
        triggerElement,
        setTriggerElement,
        channelModal,
        openChannelModal,
        closeChannelModal,
        sharedFormValues,
        setSharedFormValues,
        updateServiceInterest,
      }}
    >
      {children}
    </ModalContext.Provider>
  );
}

export function useEnquiryModal() {
  const context = useContext(ModalContext);
  if (!context) {
    throw new Error('useEnquiryModal must be used within a ModalProvider');
  }
  return context;
}
