'use client';

import React, { useState, useRef } from 'react';
import { useEnquiryModal } from '@/components/modals/ModalProvider';
import {
  ALLOWED_INTERESTS,
  ADVIORA_CONTACT,
  getServiceEnquiryMessage,
  isAutoGeneratedMessage,
  formatEnquiryPayload,
} from '@/lib/data';
import { validateField, validateAllFields, FormErrors, FormFields } from '@/lib/validation';

interface EnquiryFormProps {
  idPrefix: 'inline' | 'modal';
  isModal?: boolean;
}

export function EnquiryForm({ idPrefix, isModal = false }: EnquiryFormProps) {
  const { sharedFormValues, setSharedFormValues } = useEnquiryModal();
  const [errors, setErrors] = useState<FormErrors>({});

  const nameInputRef = useRef<HTMLInputElement>(null);
  const emailInputRef = useRef<HTMLInputElement>(null);
  const phoneInputRef = useRef<HTMLInputElement>(null);
  const interestSelectRef = useRef<HTMLSelectElement>(null);
  const messageTextareaRef = useRef<HTMLTextAreaElement>(null);

  const fieldRefs: Record<string, React.RefObject<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | null>> = {
    name: nameInputRef,
    email: emailInputRef,
    phone: phoneInputRef,
    interest: interestSelectRef,
    message: messageTextareaRef,
  };

  const handleChange = (field: keyof FormFields, value: string) => {
    if (field === 'interest') {
      setSharedFormValues((prev) => {
        const shouldUpdateMsg = isAutoGeneratedMessage(prev.message);
        const newMessage = shouldUpdateMsg ? (value ? getServiceEnquiryMessage(value) : '') : prev.message;
        return {
          ...prev,
          interest: value,
          message: newMessage,
        };
      });

      setErrors((prev) => {
        const nextErrors = { ...prev };
        if (errors.interest) {
          nextErrors.interest = validateField('interest', value);
        }
        if (errors.message && value) {
          nextErrors.message = undefined;
        }
        return nextErrors;
      });
      return;
    }

    setSharedFormValues((prev) => ({ ...prev, [field]: value }));

    if (errors[field as keyof FormErrors]) {
      const fieldError = validateField(field, value);
      setErrors((prev) => ({ ...prev, [field]: fieldError }));
    }
  };

  const validateAndGetPayload = (): string | null => {
    // Check honeypot
    if (sharedFormValues.website) {
      return null;
    }

    const { isValid, errors: validationErrors, firstInvalidField } = validateAllFields(sharedFormValues);

    if (!isValid) {
      setErrors(validationErrors);
      if (firstInvalidField && fieldRefs[firstInvalidField]?.current) {
        fieldRefs[firstInvalidField].current?.focus({ preventScroll: false });
      }
      return null;
    }

    setErrors({});
    return formatEnquiryPayload(sharedFormValues);
  };

  const handleContinueWhatsApp = (e: React.MouseEvent) => {
    e.preventDefault();
    const payload = validateAndGetPayload();
    if (!payload) return;

    const whatsappUrl = `https://wa.me/${ADVIORA_CONTACT.whatsapp}?text=${encodeURIComponent(payload)}`;
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
  };

  const handleContinueEmail = (e: React.MouseEvent) => {
    e.preventDefault();
    const payload = validateAndGetPayload();
    if (!payload) return;

    const subject = `Enquiry: ${sharedFormValues.interest} — ${sharedFormValues.name}`;
    const emailUrl = `mailto:${ADVIORA_CONTACT.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(payload)}`;
    window.location.href = emailUrl;
  };

  return (
    <form className={`form ${isModal ? 'modal-form' : ''}`} noValidate>
      <div className="fields">
        <div className="field">
          <label htmlFor={`${idPrefix}-name`}>Your name *</label>
          <input
            ref={nameInputRef}
            id={`${idPrefix}-name`}
            name="name"
            autoComplete="name"
            required
            maxLength={80}
            value={sharedFormValues.name}
            onChange={(e) => handleChange('name', e.target.value)}
            aria-invalid={Boolean(errors.name)}
            aria-describedby={errors.name ? `${idPrefix}-name-error` : undefined}
          />
          {errors.name && (
            <span id={`${idPrefix}-name-error`} className="error" role="alert">
              {errors.name}
            </span>
          )}
        </div>

        <div className="field">
          <label htmlFor={`${idPrefix}-email`}>Email address *</label>
          <input
            ref={emailInputRef}
            id={`${idPrefix}-email`}
            name="email"
            type="email"
            autoComplete="email"
            required
            maxLength={254}
            value={sharedFormValues.email}
            onChange={(e) => handleChange('email', e.target.value)}
            aria-invalid={Boolean(errors.email)}
            aria-describedby={errors.email ? `${idPrefix}-email-error` : undefined}
          />
          {errors.email && (
            <span id={`${idPrefix}-email-error`} className="error" role="alert">
              {errors.email}
            </span>
          )}
        </div>

        <div className="field">
          <label htmlFor={`${idPrefix}-phone`}>Mobile number *</label>
          <input
            ref={phoneInputRef}
            id={`${idPrefix}-phone`}
            name="phone"
            type="tel"
            autoComplete="tel"
            required
            maxLength={25}
            placeholder="e.g. +91 98765 43210"
            value={sharedFormValues.phone}
            onChange={(e) => handleChange('phone', e.target.value)}
            aria-invalid={Boolean(errors.phone)}
            aria-describedby={errors.phone ? `${idPrefix}-phone-error` : undefined}
          />
          {errors.phone && (
            <span id={`${idPrefix}-phone-error`} className="error" role="alert">
              {errors.phone}
            </span>
          )}
        </div>

        <div className="field">
          <label htmlFor={`${idPrefix}-interest`}>I’m interested in *</label>
          <select
            ref={interestSelectRef}
            id={`${idPrefix}-interest`}
            name="interest"
            required
            value={sharedFormValues.interest}
            onChange={(e) => handleChange('interest', e.target.value)}
            aria-invalid={Boolean(errors.interest)}
            aria-describedby={errors.interest ? `${idPrefix}-interest-error` : undefined}
          >
            <option value="">Choose an area</option>
            {ALLOWED_INTERESTS.map((interest) => (
              <option key={interest} value={interest}>
                {interest}
              </option>
            ))}
          </select>
          {errors.interest && (
            <span id={`${idPrefix}-interest-error`} className="error" role="alert">
              {errors.interest}
            </span>
          )}
        </div>

        <div className="field full">
          <label htmlFor={`${idPrefix}-message`}>What would you like to achieve? *</label>
          <textarea
            ref={messageTextareaRef}
            id={`${idPrefix}-message`}
            name="message"
            required
            minLength={10}
            maxLength={1500}
            placeholder="A little about your goals…"
            value={sharedFormValues.message}
            onChange={(e) => handleChange('message', e.target.value)}
            aria-invalid={Boolean(errors.message)}
            aria-describedby={errors.message ? `${idPrefix}-message-error` : undefined}
          />
          {errors.message && (
            <span id={`${idPrefix}-message-error`} className="error" role="alert">
              {errors.message}
            </span>
          )}
        </div>
      </div>

      <div className="hp" aria-hidden="true">
        <label htmlFor={`${idPrefix}-website`}>Leave empty</label>
        <input
          id={`${idPrefix}-website`}
          name="website"
          tabIndex={-1}
          autoComplete="off"
          value={sharedFormValues.website || ''}
          onChange={(e) => handleChange('website', e.target.value)}
        />
      </div>

      <div className="form-channel-actions">
        <button
          type="button"
          className="button whatsapp-submit-btn"
          onClick={handleContinueWhatsApp}
        >
          Continue on WhatsApp <span>↗</span>
        </button>
        <button
          type="button"
          className="button secondary email-submit-btn"
          onClick={handleContinueEmail}
        >
          Continue in email <span>↗</span>
        </button>
      </div>

      <p className="form-channel-note">
        Your enquiry opens in WhatsApp or your email app. Review it and send to contact our team.
      </p>
    </form>
  );
}
