'use client';

import React, { useState, useRef } from 'react';
import { useEnquiryModal } from '@/components/modals/ModalProvider';
import {
  ALLOWED_INTERESTS,
  getServiceEnquiryMessage,
  isAutoGeneratedMessage,
} from '@/lib/data';
import {
  validateField,
  validateAllFields,
  FormErrors,
  FormFields,
} from '@/lib/validation';
import { submitEnquiry } from '@/lib/submission';

interface EnquiryFormProps {
  idPrefix: 'inline' | 'modal';
  isModal?: boolean;
}

export function EnquiryForm({ idPrefix, isModal = false }: EnquiryFormProps) {
  const {
    sharedFormValues,
    setSharedFormValues,
    isSubmitting,
    setIsSubmitting,
    resetFormValues,
  } = useEnquiryModal();

  const [errors, setErrors] = useState<FormErrors>({});
  const [statusMessage, setStatusMessage] = useState<string>('');
  const [statusType, setStatusType] = useState<'success' | 'error' | null>(null);

  const nameInputRef = useRef<HTMLInputElement>(null);
  const emailInputRef = useRef<HTMLInputElement>(null);
  const phoneInputRef = useRef<HTMLInputElement>(null);
  const interestSelectRef = useRef<HTMLSelectElement>(null);
  const messageTextareaRef = useRef<HTMLTextAreaElement>(null);

  const fieldRefs: Record<
    string,
    React.RefObject<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | null>
  > = {
    name: nameInputRef,
    email: emailInputRef,
    phone: phoneInputRef,
    interest: interestSelectRef,
    message: messageTextareaRef,
  };

  const handleChange = (field: keyof FormFields, value: string) => {
    setStatusMessage('');
    setStatusType(null);

    if (field === 'interest') {
      setSharedFormValues((prev) => {
        const shouldUpdateMsg = isAutoGeneratedMessage(prev.message);
        const newMessage = shouldUpdateMsg
          ? value
            ? getServiceEnquiryMessage(value)
            : ''
          : prev.message;
        return {
          ...prev,
          interest: value,
          message: newMessage,
        };
      });

      setErrors((prev) => {
        const nextErrors = { ...prev };
        if (errors.interest) {
          nextErrors.interest = validateField('interest', value);
        }
        if (errors.message && value) {
          nextErrors.message = undefined;
        }
        return nextErrors;
      });
      return;
    }

    setSharedFormValues((prev) => ({ ...prev, [field]: value }));

    if (errors[field as keyof FormErrors]) {
      const fieldError = validateField(field, value);
      setErrors((prev) => ({ ...prev, [field]: fieldError }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (isSubmitting) return;

    // Honeypot check
    if (sharedFormValues.website) {
      // Silently clear or return
      resetFormValues();
      setStatusType('success');
      setStatusMessage('Thank you for reaching out. Your enquiry has been received.');
      return;
    }

    const { isValid, errors: validationErrors, firstInvalidField } = validateAllFields(sharedFormValues);

    if (!isValid) {
      setErrors(validationErrors);
      setStatusMessage('');
      setStatusType(null);
      if (firstInvalidField && fieldRefs[firstInvalidField]?.current) {
        fieldRefs[firstInvalidField].current?.focus({ preventScroll: false });
      }
      return;
    }

    setErrors({});
    setIsSubmitting(true);
    setStatusMessage('');
    setStatusType(null);

    try {
      const result = await submitEnquiry(sharedFormValues);

      if (result.success) {
        setStatusType('success');
        setStatusMessage(result.message || 'Thank you for reaching out. Your enquiry has been received.');
        setErrors({});
        resetFormValues();
      } else {
        setStatusType('error');
        setStatusMessage(result.message || 'Unable to submit your enquiry. Please check your details and try again.');

        if (result.fieldErrors && Object.keys(result.fieldErrors).length > 0) {
          setErrors(result.fieldErrors);
          const firstErrKey = Object.keys(result.fieldErrors)[0];
          if (firstErrKey && fieldRefs[firstErrKey]?.current) {
            fieldRefs[firstErrKey].current?.focus({ preventScroll: false });
          }
        }
      }
    } catch {
      setStatusType('error');
      setStatusMessage('Network connection failed. Please check your internet connection or reach out on WhatsApp.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form className={`form ${isModal ? 'modal-form' : ''}`} onSubmit={handleSubmit} noValidate>
      <div className="fields">
        <div className="field">
          <label htmlFor={`${idPrefix}-name`}>Your name *</label>
          <input
            ref={nameInputRef}
            id={`${idPrefix}-name`}
            name="name"
            autoComplete="name"
            required
            maxLength={60}
            value={sharedFormValues.name}
            onChange={(e) => handleChange('name', e.target.value)}
            aria-invalid={Boolean(errors.name)}
            aria-describedby={errors.name ? `${idPrefix}-name-error` : undefined}
          />
          {errors.name && (
            <span id={`${idPrefix}-name-error`} className="error" role="alert">
              {errors.name}
            </span>
          )}
        </div>

        <div className="field">
          <label htmlFor={`${idPrefix}-email`}>Email address *</label>
          <input
            ref={emailInputRef}
            id={`${idPrefix}-email`}
            name="email"
            type="email"
            autoComplete="email"
            required
            maxLength={254}
            value={sharedFormValues.email}
            onChange={(e) => handleChange('email', e.target.value)}
            aria-invalid={Boolean(errors.email)}
            aria-describedby={errors.email ? `${idPrefix}-email-error` : undefined}
          />
          {errors.email && (
            <span id={`${idPrefix}-email-error`} className="error" role="alert">
              {errors.email}
            </span>
          )}
        </div>

        <div className="field">
          <label htmlFor={`${idPrefix}-phone`}>Mobile number *</label>
          <input
            ref={phoneInputRef}
            id={`${idPrefix}-phone`}
            name="phone"
            type="tel"
            autoComplete="tel"
            required
            maxLength={20}
            placeholder="e.g. +91 98765 43210"
            value={sharedFormValues.phone}
            onChange={(e) => handleChange('phone', e.target.value)}
            aria-invalid={Boolean(errors.phone)}
            aria-describedby={errors.phone ? `${idPrefix}-phone-error` : undefined}
          />
          {errors.phone && (
            <span id={`${idPrefix}-phone-error`} className="error" role="alert">
              {errors.phone}
            </span>
          )}
        </div>

        <div className="field">
          <label htmlFor={`${idPrefix}-interest`}>I’m interested in *</label>
          <select
            ref={interestSelectRef}
            id={`${idPrefix}-interest`}
            name="interest"
            required
            value={sharedFormValues.interest}
            onChange={(e) => handleChange('interest', e.target.value)}
            aria-invalid={Boolean(errors.interest)}
            aria-describedby={errors.interest ? `${idPrefix}-interest-error` : undefined}
          >
            <option value="">Choose an area</option>
            {ALLOWED_INTERESTS.map((interest) => (
              <option key={interest} value={interest}>
                {interest}
              </option>
            ))}
          </select>
          {errors.interest && (
            <span id={`${idPrefix}-interest-error`} className="error" role="alert">
              {errors.interest}
            </span>
          )}
        </div>

        <div className="field full">
          <label htmlFor={`${idPrefix}-message`}>What would you like to achieve? *</label>
          <textarea
            ref={messageTextareaRef}
            id={`${idPrefix}-message`}
            name="message"
            required
            minLength={10}
            maxLength={600}
            placeholder="A little about your goals (10–600 characters)…"
            value={sharedFormValues.message}
            onChange={(e) => handleChange('message', e.target.value)}
            aria-invalid={Boolean(errors.message)}
            aria-describedby={errors.message ? `${idPrefix}-message-error` : undefined}
          />
          {errors.message && (
            <span id={`${idPrefix}-message-error`} className="error" role="alert">
              {errors.message}
            </span>
          )}
        </div>
      </div>

      <div className="hp" aria-hidden="true">
        <label htmlFor={`${idPrefix}-website`}>Leave empty</label>
        <input
          id={`${idPrefix}-website`}
          name="website"
          tabIndex={-1}
          autoComplete="off"
          value={sharedFormValues.website || ''}
          onChange={(e) => handleChange('website', e.target.value)}
        />
      </div>

      <button className="button" type="submit" disabled={isSubmitting}>
        {isSubmitting ? 'Sending enquiry…' : 'Send enquiry'}
      </button>

      {statusMessage && (
        <div
          className={`status ${statusType || ''}`}
          role={statusType === 'error' ? 'alert' : 'status'}
          aria-live="polite"
        >
          {statusMessage}
        </div>
      )}
    </form>
  );
}
